<a href="https://colab.research.google.com/github/AvishekPritom/Pandas-learning-path/blob/main/Pandas08_How_to_combine_data_from_multiple_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

Data loading.....

In [ ]:
air_quality_no2 = pd.read_csv("/content/air_quality_no2_long.csv", parse_dates=True)

In [ ]:
air_quality_no2 = air_quality_no2[["date.utc", "location", "parameter", "value"]]
air_quality_no2.head()

                    date.utc location parameter  value
0  2019-06-21 00:00:00+00:00  FR04014       no2   20.0
1  2019-06-20 23:00:00+00:00  FR04014       no2   21.8
2  2019-06-20 22:00:00+00:00  FR04014       no2   26.5
3  2019-06-20 21:00:00+00:00  FR04014       no2   24.9
4  2019-06-20 20:00:00+00:00  FR04014       no2   21.4

Air quality particulate matter data

In [ ]:
air_quality_pm25 = pd.read_csv("/content/air_quality_pm25_long.csv")

In [ ]:
air_quality_pm25 = air_quality_pm25[["date.utc", "location", "parameter", "value"]]
air_quality_pm25.head()

                    date.utc location parameter  value
0  2019-06-18 06:00:00+00:00  BETR801      pm25   18.0
1  2019-06-17 08:00:00+00:00  BETR801      pm25    6.5
2  2019-06-17 07:00:00+00:00  BETR801      pm25   18.5
3  2019-06-17 06:00:00+00:00  BETR801      pm25   16.0
4  2019-06-17 05:00:00+00:00  BETR801      pm25    7.5

#Concatening Objects

I want to combine the measurements of
𝑁⁢𝑂2
 and
𝑃⁢𝑀25
, two tables with a similar structure, in a single table.

In [ ]:
air_quality = pd.concat([air_quality_no2, air_quality_pm25], axis = 0)

In [ ]:
air_quality.head()

                    date.utc location parameter  value
0  2019-06-21 00:00:00+00:00  FR04014       no2   20.0
1  2019-06-20 23:00:00+00:00  FR04014       no2   21.8
2  2019-06-20 22:00:00+00:00  FR04014       no2   26.5
3  2019-06-20 21:00:00+00:00  FR04014       no2   24.9
4  2019-06-20 20:00:00+00:00  FR04014       no2   21.4

The concat() function performs concatenation operations of multiple tables along one of the axes (row-wise or column-wise).

By default concatenation is along axis 0, so the resulting table combines the rows of the input tables. Let’s check the shape of the original and the concatenated tables to verify the operation:

In [ ]:
print('Shape of the ``air_quality_pm25`` table: ', air_quality_pm25.shape)
print('Shape of the ``air_quality_no2`` table: ', air_quality_no2.shape)
print('Shape of the ``air_quality``table: ', air_quality.shape)

Shape of the ``air_quality_pm25`` table:  (1110, 4)
Shape of the ``air_quality_no2`` table:  (2068, 4)
Shape of the ``air_quality``table:  (3178, 4)



>The axis argument will return in a number of pandas methods that can be applied along an axis. A DataFrame has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1). Most operations like concatenation or summary statistics are by default across rows (axis 0), but can be applied across columns as well.

Sorting the table on the datetime information also illustrates the combination of both tables, with the parameter column defining the origin of the table (either no2 from table air_quality_no2 or pm25 from table air_quality_pm25):

In [ ]:
air_quality.sort_values("date.utc")

                       date.utc            location parameter  value
1109  2019-05-07 01:00:00+00:00  London Westminster      pm25    8.0
2067  2019-05-07 01:00:00+00:00  London Westminster       no2   23.0
1098  2019-05-07 01:00:00+00:00             BETR801       no2   50.5
1003  2019-05-07 01:00:00+00:00             FR04014       no2   25.0
100   2019-05-07 01:00:00+00:00             BETR801      pm25   12.5
...                         ...                 ...       ...    ...
2     2019-06-20 22:00:00+00:00             FR04014       no2   26.5
102   2019-06-20 23:00:00+00:00  London Westminster      pm25    7.0
1     2019-06-20 23:00:00+00:00             FR04014       no2   21.8
101   2019-06-21 00:00:00+00:00  London Westminster      pm25    7.0
0     2019-06-21 00:00:00+00:00             FR04014       no2   20.0

[3178 rows x 4 columns]

In [ ]:
air_quality_ = pd.concat([air_quality_pm25, air_quality_no2], keys=["PM25", "NO2"])

In [ ]:
air_quality.head()

                    date.utc location parameter  value
0  2019-06-21 00:00:00+00:00  FR04014       no2   20.0
1  2019-06-20 23:00:00+00:00  FR04014       no2   21.8
2  2019-06-20 22:00:00+00:00  FR04014       no2   26.5
3  2019-06-20 21:00:00+00:00  FR04014       no2   24.9
4  2019-06-20 20:00:00+00:00  FR04014       no2   21.4

#Join tables using a common identifier

Add the station coordinates, provided by the stations metadata table, to the corresponding rows in the measurements table.

In [ ]:
air_quality = pd.merge(air_quality_no2, air_quality_pm25, how='left', on='location')

In [ ]:
air_quality.head()

,date.utc_x,location,parameter_x,value_x,date.utc_y,parameter_y,value_y
0,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,NaN,NaN,NaN
1,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,NaN,NaN,NaN
2,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,NaN,NaN,NaN
3,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,NaN,NaN,NaN
4,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,NaN,NaN,NaN

In [ ]:
air_quality = pd.merge(air_quality_no2, air_quality_pm25, how ="left", left_on="location", right_on="parameter")

In [ ]:
air_quality.head()

,date.utc_x,location_x,parameter_x,value_x,date.utc_y,location_y,parameter_y,value_y
0,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,NaN,NaN,NaN,NaN
1,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,NaN,NaN,NaN,NaN
2,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,NaN,NaN,NaN,NaN
3,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,NaN,NaN,NaN,NaN
4,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,NaN,NaN,NaN,NaN

Compared to the previous example, there is no common column name. However, the parameter column in the air_quality table and the id column in the air_quality_parameters table both provide the measured variable in a common format. The left_on and right_on arguments are used here (instead of just on) to make the link between the two tables.